<?

define('PARENT_TYPE_YES_NO', 100);
define('TYPE_YES_NO_YES', 101);
define('TYPE_YES_NO_NO', 102);

define('PARENT_TYPE_ENTITY', 200);


define('PARENT_TYPE_CUSTOM_CONTENT', 500);

//@TODO - should these be divided into separate statuses?
define('PARENT_TYPE_STATUS', 700);
define('TYPE_STATUS_ACTIVE', 701);
define('TYPE_STATUS_ALUMNI', 702);
define('TYPE_STATUS_FIRED', 703);
define('TYPE_STATUS_DELETED', 704);
define('TYPE_STATUS_NEW', 705);

define('PARENT_TYPE_PREFERENCES', 800);
define('TYPE_PREFERENCE_CALENDAR', 801);
define('TYPE_PREFERENCE_SPECIALS', 802);
define('TYPE_PREFERENCE_FACEBOOK', 805);
define('TYPE_PREFERENCE_WEBSITE', 806); // for whether the bar has ability to edit its site
define('TYPE_PREFERENCE_DOMAIN', 807); // perhaps this should be an attribute
define('TYPE_PREFERENCE_PHOTOS', 808);
define('TYPE_PREFERENCE_HOMEPAGE_MSG', 809);

define('PARENT_TYPE_XREF', 900);
define('TYPE_XREF_BAR', 901);

define('PARENT_TYPE_INTERVAL', 1000);
define('TYPE_INTERVAL_ONE_TIME', 1001);
define('TYPE_INTERVAL_DAILY', 1002);
define('TYPE_INTERVAL_WEEKLY', 1003);
define('TYPE_INTERVAL_MONTHLY', 1004);
define('TYPE_INTERVAL_QUARTERLY', 1005);
define('TYPE_INTERVAL_YEARLY', 1006);
define('TYPE_INTERVAL_BIWEEKLY', 1007);
define('TYPE_INTERVAL_BIMONTHLY', 1008);
define('TYPE_INTERVAL_DATE_RANGE', 1009);
define('TYPE_INTERVAL_MULTI_DATES', 1010);

define('PARENT_TYPE_DAY', 1100);
define('TYPE_DAY_MON', 1101);
define('TYPE_DAY_TUE', 1102);
define('TYPE_DAY_WED', 1103);
define('TYPE_DAY_THU', 1104);
define('TYPE_DAY_FRI', 1105);
define('TYPE_DAY_SAT', 1106);
define('TYPE_DAY_SUN', 1107);

define('PARENT_TYPE_MIME', 1200);
define('TYPE_MIME_PNG', 1201);
define('TYPE_MIME_JPG', 1202);
define('TYPE_MIME_GIF', 1203);

define('PARENT_TYPE_ATTRIBUTE', 1300);
define('TYPE_ATTRIBUTE_FB_ID', 1301);
define('TYPE_ATTRIBUTE_FB_SECRET', 1302);

define('PARENT_TYPE_LOG', 1400);
define('TYPE_LOG_MSG', 1401);
define('TYPE_LOG_PHP_ERROR', 1402);
define('TYPE_LOG_JS_ERROR', 1403);
define('TYPE_LOG_SQL_ERROR', 1404);
define('TYPE_LOG_SQL_SLOW', 1405);
define('TYPE_LOG_DEPRECATED', 1406);

define('PARENT_TYPE_LOG_PRIORITY', 1500);
define('TYPE_LOG_PRIORITY_LOW', 1501);
define('TYPE_LOG_PRIORITY_MEDIUM', 1501);
define('TYPE_LOG_PRIORITY_HIGH', 1501);
define('TYPE_LOG_PRIORITY_CRITICAL', 1501);
define('TYPE_LOG_PRIORITY_EMERGENCY', 1501);

define('PARENT_TYPE_SCHEDULER_STATUS', 1600);
define('TYPE_SCHEDULER_STATUS_DISABLED', 1601);
define('TYPE_SCHEDULER_STATUS_READY', 1602);
define('TYPE_SCHEDULER_STATUS_RUNNING', 1603);

define('PARENT_TYPE_EMAIL_PRIORITY', 1700);
define('TYPE_EMAIL_PRIORITY_LAST', 1701);
define('TYPE_EMAIL_PRIORITY_LOW', 1702);
define('TYPE_EMAIL_PRIORITY_NORMAL', 1703);
define('TYPE_EMAIL_PRIORITY_URGENT', 1704);
define('TYPE_EMAIL_PRIORITY_IMMEDIATE', 1705);

define('PARENT_TYPE_EMAIL_STATUS', 1800);
define('TYPE_EMAIL_STATUS_ERROR', 1801);
define('TYPE_EMAIL_STATUS_UNSENT', 1802);
define('TYPE_EMAIL_STATUS_QUEUED', 1803);
define('TYPE_EMAIL_STATUS_SENT', 1804);
